name: EProspera Home - Test, Build, Push, Deploy to AWS

on:
    workflow_dispatch: {}
    push:
        branches:
            - main
permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test